import { readSecretsFile, type SecretsBundle } from "@/lib/openclaw-secrets";
import { getOrCreateGatewayToken } from "@/lib/gateway-token-source";
import { getOrCreatePluginSecret } from "@/lib/plugin-secrets-source";
import { PROVIDERS } from "@/lib/providers";
import { getSetting } from "@/lib/settings";

// Central home for the runtime-secret pipeline that feeds openclaw.json
// + secrets.json. Owns the Pattern A/B/C secret-handling matrix from
// CLAUDE.md "Secrets Handling":
//
//   Pattern A — OpenClaw built-in resolves SecretRef
//     LLM provider apiKey via SecretRef in models.providers.<name>.apiKey.
//     `collectProviderSecrets()` walks PROVIDERS for configured keys
//     and writes provider secrets + env values (backward-compat) to secrets.json.
//
//   Pattern B — Pinchy plugins fetch via API
//     Per-integration credentials (Odoo, web-search, email).
//     Not collected here — the plugin reads `connectionId` from
//     openclaw.json and calls /api/internal/integrations/.../credentials
//     at runtime. See pinchy-odoo / pinchy-email / pinchy-web.
//
//   Pattern C — Bootstrap credentials (plaintext, single source)
//     Gateway auth token and plugin gatewayToken values.
//     `readGatewayTokenFromConfig()` extracts the token from existing
//     openclaw.json (preferred) or secrets.json (fallback). Cannot
//     itself be fetched via Pinchy's API (chicken-and-egg).
//
// Future audit, rotation, and validation logic for any of these
// patterns belongs in this file.

export interface ProviderSecretsCollection {
  /** Per-provider apiKey for `secrets.json#/providers`. */
  providers: Record<string, { apiKey: string }>;
}

/**
 * Walk PROVIDERS for configured API keys and produce the secrets-bundle
 * pair (Pattern A from CLAUDE.md "Secrets Handling").
 *
 * For each provider with an apiKey set in settings, emits:
 *   - providers.<providerKey> = { apiKey }   (into secrets.json — resolved
 *     live via SecretRef in models.providers.<name>.apiKey)
 *
 * Returns a fresh, mutable map owned by the caller. The caller may
 * splice in additional entries (e.g. ollama-cloud, handled at the
 * model-providers call site in build.ts).
 */
export async function collectProviderSecrets(): Promise<ProviderSecretsCollection> {
  const providers: Record<string, { apiKey: string }> = {};
  for (const [providerKey, providerConfig] of Object.entries(PROVIDERS)) {
    // URL-auth providers (ollama-local) have no API key — their settings value
    // is a base URL. Emitting it as providers.<name>.apiKey writes a phantom
    // "credential" into secrets.json that nothing resolves and that misleads
    // rotation/audit tooling. Only collect real api-key providers.
    if (providerConfig.authType === "url") continue;
    const apiKey = await getSetting(providerConfig.settingsKey);
    if (apiKey) {
      providers[providerKey] = { apiKey };
    }
  }
  return { providers };
}

/**
 * Return the gateway auth token (Pattern C), with the DB as the source of truth.
 *
 * Phase 3.3: `getOrCreateGatewayToken()` is the primary source — it returns
 * the token persisted in the settings DB (seeded by migrateGatewayTokenToDb()
 * on first boot, generated by getOrCreateGatewayToken() on fresh installs).
 * The existing-config and secrets.json paths are fallbacks for the narrow
 * window where the DB is unavailable (pre-setup cold-start).
 *
 * The token must be a literal string in `gateway.auth.token` (OpenClaw
 * refuses SecretRef objects in that path) and is mirrored to
 * `secrets.json#/gateway/token` so Pinchy can authenticate its own RPCs.
 */
export async function readGatewayTokenFromConfig(
  existing: Record<string, unknown>
): Promise<string | undefined> {
  try {
    const dbToken = await getOrCreateGatewayToken();
    if (dbToken) return dbToken;
  } catch {
    // DB unavailable (pre-setup) — fall through to legacy sources.
  }

  const existingGateway = (existing.gateway as Record<string, unknown>) || {};
  const existingAuth = (existingGateway.auth as Record<string, unknown>) || {};
  return typeof existingAuth.token === "string"
    ? existingAuth.token
    : readSecretsFile().gateway?.token;
}

/**
 * Collect per-plugin shared secrets that pinchy-* plugins need at runtime
 * (Pattern A-prime in the secrets matrix — not OC-resolved SecretRefs because
 * OC 2026.4.x doesn't walk SecretRefs in arbitrary plugin config trees, but
 * also not Pattern B because these aren't customer integration credentials).
 *
 * Each entry is generated once and persisted in the settings DB via
 * `getOrCreatePluginSecret`, then materialised into `secrets.json` so the
 * OC-side plugin can read it from the shared volume.
 *
 * Current entries:
 *   - pinchy-odoo.refTokenKey — AES-256-GCM key for encrypting opaque
 *     integration-ref tokens (replaces the broken /app/secrets fallback that
 *     never existed in the OC container).
 *
 * Add new plugin secrets here whenever a plugin needs a symmetric key that
 * must match between pinchy-web and the OC-side plugin code.
 */
export async function collectPluginSecrets(): Promise<{
  plugins: Record<string, Record<string, string>>;
}> {
  const refTokenKey = await getOrCreatePluginSecret("pinchy-odoo:ref-token-key");
  return {
    plugins: {
      "pinchy-odoo": { refTokenKey },
    },
  };
}

/**
 * Assemble the runtime SecretsBundle written to secrets.json.
 *
 * Each input is collected upstream during config building:
 *   - gateway:      Pattern C bootstrap token (readGatewayTokenFromConfig)
 *   - providers:    Pattern A LLM-provider keys (collectProviderSecrets)
 *   - integrations: Pattern B placeholder (live integrations fetch via
 *                   /api/internal/integrations/.../credentials)
 *   - plugins:      Per-plugin shared secrets (collectPluginSecrets)
 *   - env:          Pattern A resolved env-var values (collectProviderSecrets)
 */
export function buildSecretsBundle(parts: {
  gateway: SecretsBundle["gateway"];
  providers: SecretsBundle["providers"];
  integrations: SecretsBundle["integrations"];
  plugins?: SecretsBundle["plugins"];
}): SecretsBundle {
  return {
    gateway: parts.gateway,
    providers: parts.providers,
    integrations: parts.integrations,
    ...(parts.plugins ? { plugins: parts.plugins } : {}),
  };
}
