// AUTO-GENERATED by scripts/generate-docs-paths.mjs — do not edit manually.
// Run: pnpm docs:paths

export const DOCS_PATHS = [
  "architecture",
  "concepts/agent-permissions",
  "concepts/agent-settings",
  "concepts/audit-trail",
  "concepts/context",
  "concepts/groups",
  "concepts/integrations",
  "concepts/philosophy",
  "concepts/user-roles",
  "explanation/agent-memory",
  "getting-started",
  "guides/connect-email",
  "guides/connect-odoo",
  "guides/create-knowledge-base-agent",
  "guides/deploy-digitalocean",
  "guides/deploy-hetzner",
  "guides/domain-lock",
  "guides/enterprise-setup",
  "guides/hardening",
  "guides/llm-providers",
  "guides/mount-data-directories",
  "guides/ollama-setup",
  "guides/smithers-onboarding",
  "guides/telegram-setup",
  "guides/upgrading",
  "guides/usage-dashboard",
  "guides/user-management",
  "guides/vps-deployment",
  "installation",
  "reference/api",
  "reference/sbom",
] as const;

export type DocsPath = (typeof DOCS_PATHS)[number];
