import { randomBytes } from "crypto";
import { getSetting, setSetting } from "@/lib/settings";

const SETTING_KEY = "openclaw_gateway_token";

/**
 * Returns the gateway auth token, generating and persisting a new one if none
 * exists in the settings table. The token is 48 hex chars (24 random bytes),
 * matching the shape generated by config/ensure-gateway-token.js.
 *
 * Phase 3 of the cold-start architecture: Pinchy owns the token in the DB so
 * Phase 4 (OpenClaw depends_on Pinchy) can write the final config before
 * OpenClaw starts, eliminating the bootstrap-script-generated token and the
 * SIGUSR1 that followed it (Restart #1).
 */
export async function getOrCreateGatewayToken(): Promise<string> {
  const existing = await getSetting(SETTING_KEY);
  if (existing) return existing;

  const token = randomBytes(24).toString("hex");
  await setSetting(SETTING_KEY, token);
  return token;
}
