/**
 * Reading and rewriting the gitignored `.env` that gives a worktree its own
 * dev-stack ports.
 *
 * Two things here are easy to get wrong and both were:
 *
 *   - Rewriting must REPLACE the generated block, not append a second one.
 *     The first version filtered by key name only, so the comment header
 *     survived every `--force` and the file grew a duplicate header per run.
 *   - A `.env` written by the FIRST version of the script names its keys
 *     PINCHY_PORT / DB_PORT / CADDY_PORT. Those leak out of the dev stack into
 *     every E2E stack that layers on `docker-compose.yml`, which is why they
 *     were renamed to DEV_*. Leaving the old keys behind would keep the bug
 *     alive on exactly the machines that already ran the old script — so the
 *     rewrite has to clean them up, not just stop writing them.
 */
import { test } from "node:test";
import assert from "node:assert/strict";

import { parseEnvFile, writeManagedBlock } from "./env-file.mjs";

// ---------------------------------------------------------------------------
// parseEnvFile
// ---------------------------------------------------------------------------

test("reads plain KEY=value lines", () => {
  assert.deepEqual(parseEnvFile("A=1\nB=two\n"), { A: "1", B: "two" });
});

test("ignores comments and blank lines", () => {
  assert.deepEqual(parseEnvFile("# note\n\nA=1\n"), { A: "1" });
});

test("understands the forms people actually write in a .env", () => {
  // `export` prefixes, quoting and stray whitespace all appear in hand-written
  // .env files. Misreading one means the script thinks a key is missing and
  // silently re-allocates the worktree's ports.
  assert.deepEqual(
    parseEnvFile(
      ["export A=1", 'B="two words"', "C='three'", "  D = 4  ", ""].join("\n"),
    ),
    { A: "1", B: "two words", C: "three", D: "4" },
  );
});

// ---------------------------------------------------------------------------
// writeManagedBlock
// ---------------------------------------------------------------------------

const ENTRIES = {
  COMPOSE_PROJECT_NAME: "kb-sources-ui",
  DEV_PINCHY_PORT: "127.0.0.1:7830",
  DEV_DB_PORT: "5487",
  DEV_CADDY_PORT: "8496",
};

test("keeps what the developer wrote and appends the generated block", () => {
  const out = writeManagedBlock("MY_OWN=keepme\n", ENTRIES);
  assert.match(out, /^MY_OWN=keepme$/m);
  assert.equal(parseEnvFile(out).DEV_DB_PORT, "5487");
  assert.equal(parseEnvFile(out).MY_OWN, "keepme");
});

test("rewriting replaces the generated block instead of stacking copies", () => {
  // The reproduced bug: three runs left three copies of the comment header.
  let out = writeManagedBlock("MY_OWN=keepme\n", ENTRIES);
  out = writeManagedBlock(out, { ...ENTRIES, DEV_DB_PORT: "5490" });
  out = writeManagedBlock(out, { ...ENTRIES, DEV_DB_PORT: "5491" });

  const headers = out.match(/worktree-env\.mjs/g) ?? [];
  assert.equal(headers.length, 1, "generated header must appear exactly once");
  assert.equal(parseEnvFile(out).DEV_DB_PORT, "5491");
  assert.equal(parseEnvFile(out).MY_OWN, "keepme");
});

test("cleans up a .env left behind by the first version of the script", () => {
  // Verbatim shape the old script produced — no markers, and the pre-rename
  // key names. Written as pre-existing data, then read by the new code.
  const legacy = [
    "MY_OWN=keepme",
    "",
    "# Per-worktree dev stack — generated by scripts/worktree-env.mjs.",
    "# Lets this worktree's stack run alongside others. Safe to delete and regenerate.",
    "COMPOSE_PROJECT_NAME=kb-sources-ui",
    "PINCHY_PORT=127.0.0.1:7789",
    "DB_PORT=5446",
    "CADDY_PORT=8455",
    "",
  ].join("\n");

  const out = writeManagedBlock(legacy, ENTRIES);
  const parsed = parseEnvFile(out);

  // The renamed keys are what the dev overlay reads now.
  assert.equal(parsed.DEV_PINCHY_PORT, "127.0.0.1:7830");
  assert.equal(parsed.DEV_DB_PORT, "5487");
  assert.equal(parsed.DEV_CADDY_PORT, "8496");
  // The old ones must be GONE — a leftover PINCHY_PORT still moves every E2E
  // stack off :7777, which is the bug the rename exists to fix.
  assert.equal(parsed.PINCHY_PORT, undefined);
  assert.equal(parsed.DB_PORT, undefined);
  assert.equal(parsed.CADDY_PORT, undefined);
  // And the developer's own line survives the migration.
  assert.equal(parsed.MY_OWN, "keepme");
  assert.doesNotMatch(out, /^# Per-worktree dev stack/m);
});

test("does not touch a PINCHY_PORT the developer set themselves", () => {
  // Only a GENERATED block is rewritten. A bare PINCHY_PORT outside one is a
  // deliberate production-style override (installation.mdx documents it) and
  // deleting it would be an unpleasant surprise.
  const mine = "PINCHY_PORT=0.0.0.0:80\nMY_OWN=keepme\n";
  const parsed = parseEnvFile(writeManagedBlock(mine, ENTRIES));
  assert.equal(parsed.PINCHY_PORT, "0.0.0.0:80");
  assert.equal(parsed.DEV_PINCHY_PORT, "127.0.0.1:7830");
});

test("produces a file that ends in exactly one newline", () => {
  const out = writeManagedBlock("MY_OWN=keepme\n\n\n", ENTRIES);
  assert.match(out, /[^\n]\n$/);
});
