/**
 * Reading and rewriting the gitignored `.env` that gives a worktree its own
 * dev-stack ports.
 *
 * Kept separate from the allocator so both stay testable without touching the
 * filesystem, and so `vitest.integration.config.ts` can reuse the parser to
 * find the dev database rather than re-implementing it.
 */

/** Keys the generated block owns. Anything else in `.env` is the developer's. */
export const MANAGED_KEYS = [
  "COMPOSE_PROJECT_NAME",
  "DEV_PINCHY_PORT",
  "DEV_DB_PORT",
  "DEV_CADDY_PORT",
];

/**
 * Key names the FIRST version of this script wrote. They were renamed because
 * `PINCHY_PORT`, `DB_PORT` and `CADDY_PORT` are read by `docker-compose.yml`
 * itself, so a dev-stack allocation leaked into every E2E stack layered on it
 * and moved Pinchy off the :7777 the Playwright configs expect.
 *
 * Only ever removed from INSIDE a generated block — a bare `PINCHY_PORT` a
 * developer set themselves is a documented production override, not ours.
 */
const LEGACY_KEYS = ["PINCHY_PORT", "DB_PORT", "CADDY_PORT"];

const BEGIN = "# >>> pinchy per-worktree dev stack >>>";
const END = "# <<< pinchy per-worktree dev stack <<<";
const LEGACY_HEADER = /^#\s*Per-worktree dev stack/;

/**
 * Parse a `.env` into a plain object, tolerating the forms people actually
 * write: `export FOO=bar`, quoted values, and stray whitespace. Misreading one
 * would make the script believe a key is missing and re-allocate ports that
 * were meant to stay put.
 *
 * The JSDoc types are load-bearing, not decoration: `vitest.integration.config.ts`
 * imports this, and that file IS part of what `next build` type-checks. Without
 * them TypeScript infers `{}` for the return value and the build fails with
 * TS2339 on the first property access.
 *
 * @param {string} text
 * @returns {Record<string, string>}
 */
export function parseEnvFile(text) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const line of text.split("\n")) {
    const m = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/.exec(
      line,
    );
    if (!m) continue;
    const [, key, rawValue] = m;
    const quoted = /^(["'])(.*)\1$/.exec(rawValue);
    out[key] = quoted ? quoted[2] : rawValue;
  }
  return out;
}

/** Drop the marked block, if this file already has one. */
function stripMarkedBlock(lines) {
  const start = lines.findIndex((l) => l.trim() === BEGIN);
  if (start === -1) return lines;
  const end = lines.findIndex((l, i) => i > start && l.trim() === END);
  return end === -1
    ? lines.slice(0, start)
    : [...lines.slice(0, start), ...lines.slice(end + 1)];
}

/**
 * Drop a block written before the markers existed: the old comment header plus
 * the contiguous run of generated keys under it. Bounded to that run so a
 * developer's own settings further down the file are never swept up.
 */
function stripLegacyBlock(lines) {
  const start = lines.findIndex((l) => LEGACY_HEADER.test(l));
  if (start === -1) return lines;

  const generated = new Set([...MANAGED_KEYS, ...LEGACY_KEYS]);
  let end = start;
  while (end < lines.length) {
    const line = lines[end];
    const key = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(line);
    const isOurs = key ? generated.has(key[1]) : line.trim().startsWith("#");
    if (!isOurs) break;
    end++;
  }
  return [...lines.slice(0, start), ...lines.slice(end)];
}

/**
 * Return `existing` with the generated block replaced by one holding
 * `entries`. Everything the developer wrote is preserved in place.
 *
 * @param {string} existing
 * @param {Record<string, string>} entries
 * @returns {string}
 */
export function writeManagedBlock(existing, entries) {
  const kept = stripLegacyBlock(stripMarkedBlock(existing.split("\n")))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

  const block = [
    BEGIN,
    "# Generated by scripts/worktree-env.mjs — lets this worktree's stack run",
    "# alongside others. Safe to delete and regenerate (pnpm worktree:env).",
    ...Object.entries(entries).map(([k, v]) => `${k}=${v}`),
    END,
  ].join("\n");

  return (kept ? `${kept}\n\n` : "") + block + "\n";
}
