#!/usr/bin/env node
/**
 * Write a gitignored `.env` giving THIS worktree its own dev-stack ports, so it
 * can run alongside other worktrees' stacks.
 *
 *   node scripts/worktree-env.mjs          # allocate once, keep what exists
 *   node scripts/worktree-env.mjs --force  # re-allocate (ports moved / conflict)
 *
 * Compose reads `.env` from the project directory automatically, so after this
 * the ordinary command works unchanged:
 *
 *   docker compose -f docker-compose.yml -f docker-compose.dev.yml up
 *
 * Existing keys are never rewritten without `--force`: the address of a
 * worktree should stay bookmarkable, and re-probing on every run would move it
 * as soon as an unrelated stack briefly held one of its ports.
 */
import { createServer } from "node:net";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { execFileSync } from "node:child_process";

import {
  projectSlug,
  allocatePorts,
  PORT_FAMILIES,
  MAX_BLOCKS,
} from "./lib/worktree-ports.mjs";

const MANAGED_KEYS = [
  "COMPOSE_PROJECT_NAME",
  "PINCHY_PORT",
  "DB_PORT",
  "CADDY_PORT",
];

function worktreeRoot() {
  try {
    return execFileSync("git", ["rev-parse", "--show-toplevel"], {
      encoding: "utf8",
    }).trim();
  } catch {
    return process.cwd();
  }
}

/** Free means: we can bind it right now. Anything else is a reason to move on. */
function probePort(port) {
  return new Promise((resolve) => {
    const s = createServer();
    s.once("error", () => resolve(false));
    s.listen(port, "0.0.0.0", () => s.close(() => resolve(true)));
  });
}

/**
 * Probe every port `allocatePorts` could ask about, up front and concurrently,
 * so the allocator itself stays a pure synchronous function with a plain
 * predicate — and so this costs one pass instead of one probe per candidate.
 */
async function freePorts() {
  const candidates = [];
  for (const base of Object.values(PORT_FAMILIES)) {
    for (let i = 0; i < MAX_BLOCKS; i++) candidates.push(base + i);
  }
  const results = await Promise.all(candidates.map(probePort));
  return new Set(candidates.filter((_, i) => results[i]));
}

function parseEnv(text) {
  const out = {};
  for (const line of text.split("\n")) {
    const m = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

const root = worktreeRoot();
const envPath = join(root, ".env");
const force = process.argv.includes("--force");
const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
const parsed = parseEnv(existing);

if (!force && MANAGED_KEYS.every((k) => k in parsed)) {
  console.log(
    `.env already allocates this worktree — leaving it alone (--force to re-allocate).`,
  );
  for (const k of MANAGED_KEYS) console.log(`  ${k}=${parsed[k]}`);
  process.exit(0);
}

const slug = projectSlug(root);
const free = await freePorts();
const ports = allocatePorts(slug, (port) => free.has(port));

// Preserve anything the developer put in .env themselves; replace only ours.
const kept = existing
  .split("\n")
  .filter(
    (l) => !MANAGED_KEYS.some((k) => new RegExp(`^\\s*${k}\\s*=`).test(l)),
  )
  .join("\n")
  .replace(/\n{3,}/g, "\n\n")
  .trim();

const block = [
  "# Per-worktree dev stack — generated by scripts/worktree-env.mjs.",
  "# Lets this worktree's stack run alongside others. Safe to delete and regenerate.",
  `COMPOSE_PROJECT_NAME=${slug}`,
  `PINCHY_PORT=127.0.0.1:${ports.pinchyPort}`,
  `DB_PORT=${ports.dbPort}`,
  `CADDY_PORT=${ports.caddyPort}`,
].join("\n");

writeFileSync(envPath, (kept ? `${kept}\n\n` : "") + block + "\n");

console.log(`Allocated block +${ports.offset} for "${slug}":`);
console.log(`  Pinchy    http://localhost:${ports.pinchyPort}`);
console.log(`  Postgres  localhost:${ports.dbPort}`);
console.log(`  Caddy     https://localhost:${ports.caddyPort}`);
console.log(`\nWritten to ${envPath}. Bases: ${JSON.stringify(PORT_FAMILIES)}`);
